In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.0'

## Part 1 - Data Preprocessing

In [3]:
train=pd.read_csv("new_train.csv")
train.drop(columns=["Unnamed: 0"],inplace=True)
train

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other,damage_grade
0,802906,6,487,12198,2,30,6,5,t,r,...,0,0,0,0,0,0,0,0,0,3
1,28830,8,900,2812,2,10,8,7,o,r,...,0,0,0,0,0,0,0,0,0,2
2,94947,21,363,8973,2,10,5,5,t,r,...,0,0,0,0,0,0,0,0,0,3
3,590882,22,418,10694,2,10,6,5,t,r,...,0,0,0,0,0,0,0,0,0,2
4,201944,11,131,1488,3,30,8,9,t,r,...,0,0,0,0,0,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,688636,25,1335,1621,1,55,6,3,n,r,...,0,0,0,0,0,0,0,0,0,2
260597,669485,17,715,2060,2,0,6,5,t,r,...,0,0,0,0,0,0,0,0,0,3
260598,602512,17,51,8163,3,55,6,7,t,r,...,0,0,0,0,0,0,0,0,0,3
260599,151409,26,39,1851,2,10,14,6,t,r,...,0,0,0,0,0,0,0,0,0,2
260600,747594,21,9,9101,3,10,7,6,n,r,...,0,0,0,0,0,0,0,0,0,3

In [4]:
arr=train.columns.values
print(np.where(arr=="legal_ownership_status"))

(array([26], dtype=int64),)

In [5]:
X=train.iloc[:,:-1]
y=train.iloc[:,-1]

In [6]:
X

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
1,28830,8,900,2812,2,10,8,7,o,r,...,0,0,0,0,0,0,0,0,0,0
2,94947,21,363,8973,2,10,5,5,t,r,...,0,0,0,0,0,0,0,0,0,0
3,590882,22,418,10694,2,10,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
4,201944,11,131,1488,3,30,8,9,t,r,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,688636,25,1335,1621,1,55,6,3,n,r,...,0,0,0,0,0,0,0,0,0,0
260597,669485,17,715,2060,2,0,6,5,t,r,...,0,0,0,0,0,0,0,0,0,0
260598,602512,17,51,8163,3,55,6,7,t,r,...,0,0,0,0,0,0,0,0,0,0
260599,151409,26,39,1851,2,10,14,6,t,r,...,0,0,0,0,0,0,0,0,0,0
260600,747594,21,9,9101,3,10,7,6,n,r,...,0,0,0,0,0,0,0,0,0,0

In [7]:
X.columns.values

array(['building_id', 'geo_level_1_id', 'geo_level_2_id',
       'geo_level_3_id', 'count_floors_pre_eq', 'age', 'area_percentage',
       'height_percentage', 'land_surface_condition', 'foundation_type',
       'roof_type', 'ground_floor_type', 'other_floor_type', 'position',
       'plan_configuration', 'has_superstructure_adobe_mud',
       'has_superstructure_mud_mortar_stone',
       'has_superstructure_stone_flag',
       'has_superstructure_cement_mortar_stone',
       'has_superstructure_mud_mortar_brick',
       'has_superstructure_cement_mortar_brick',
       'has_superstructure_timber', 'has_superstructure_bamboo',
       'has_superstructure_rc_non_engineered',
       'has_superstructure_rc_engineered', 'has_superstructure_other',
       'legal_ownership_status', 'count_families', 'has_secondary_use',
       'has_secondary_use_agriculture', 'has_secondary_use_hotel',
       'has_secondary_use_rental', 'has_secondary_use_institution',
       'has_secondary_use_school', 'has_secondary_use_industry',
       'has_secondary_use_health_post', 'has_secondary_use_gov_office',
       'has_secondary_use_use_police', 'has_secondary_use_other'],
      dtype=object)

In [8]:
X_cat=X[["land_surface_condition","foundation_type",'roof_type','ground_floor_type','other_floor_type','plan_configuration','position','legal_ownership_status']].copy()
X_cat

,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,plan_configuration,position,legal_ownership_status
0,t,r,n,f,q,d,t,v
1,o,r,n,x,q,d,s,v
2,t,r,n,f,x,d,t,v
3,t,r,n,f,x,d,s,v
4,t,r,n,f,x,d,s,v
...,...,...,...,...,...,...,...,...
260596,n,r,n,f,j,q,s,v
260597,t,r,n,f,q,d,s,v
260598,t,r,q,f,q,d,s,v
260599,t,r,x,v,s,d,j,v
260600,n,r,n,f,q,d,j,v

In [9]:
X_ids=X[['building_id', 'geo_level_1_id', 'geo_level_2_id',
       'geo_level_3_id']].copy()
X_ids

        building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id
0            802906               6             487           12198
1             28830               8             900            2812
2             94947              21             363            8973
3            590882              22             418           10694
4            201944              11             131            1488
...             ...             ...             ...             ...
260596       688636              25            1335            1621
260597       669485              17             715            2060
260598       602512              17              51            8163
260599       151409              26              39            1851
260600       747594              21               9            9101

[260601 rows x 4 columns]

In [10]:
X_rem=X.drop(columns=['building_id', 'geo_level_1_id', 'geo_level_2_id',
       'geo_level_3_id',"land_surface_condition","foundation_type",'roof_type','position','ground_floor_type','other_floor_type','plan_configuration','legal_ownership_status'])
X_rem

,count_floors_pre_eq,age,area_percentage,height_percentage,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,2,30,6,5,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,10,8,7,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,10,5,5,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,10,6,5,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3,30,8,9,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,1,55,6,3,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260597,2,0,6,5,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260598,3,55,6,7,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
260599,2,10,14,6,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
260600,3,10,7,6,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
# for i in X_rem.columns:
#     print(X_rem[i])

In [12]:
X_ids.shape

(260601, 4)

In [13]:
X_cat.shape

(260601, 8)

In [14]:
X.shape

(260601, 39)

**We need to use one-hot encoding for categorical data**
land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration
,position,plan_configuration

In [15]:
from sklearn.preprocessing import OneHotEncoder
X_cat=OneHotEncoder().fit_transform(X_cat).toarray()

### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_rem=sc.fit_transform(X_rem)

### Merging all the three different into one

In [17]:
X=np.concatenate((X_ids,X_rem,X_cat),axis=1)
X.shape

(260601, 69)

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training and testing data

**Logistic Regression**

In [19]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=20000)

In [20]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=20000)

In [21]:
model.score(X_test,y_test)

0.5698854588361697

**RandomForestClassifier**

In [22]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [23]:
model.score(X_test,y_test)

0.7160837282477313

In [24]:
y_pred=model.predict(X_test)

**Decision Tree**

In [25]:
from sklearn import tree
model=tree.DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [26]:
 model.score(X_test,y_test)

0.6504863682584755

### The predicted data of Random Forest Classifier is giving the best accuracy